zookeeper:
  user: cp-kafka
  group: confluent
  config_file: /etc/kafka/zookeeper.properties
  service_name: confluent-zookeeper
  systemd_override: /etc/systemd/system/confluent-zookeeper.service.d
  config:
    maxClientCnxns: 0
    initLimit: 5
    syncLimit: 2
    autopurge.snapRetainCount: 10
    autopurge.purgeInterval: 1
    dataDir: /var/lib/zookeeper
    clientPort: 2181
  environment:
    KAFKA_HEAP_OPTS: "-Xmx256M"
  systemd:
    enabled: yes
    state: started
